// NOTE:
// We keep the full master list below as ALL_COUNTRY_CODES, but only export a
// filtered list (COUNTRY_CODES) that includes: USA, Canada, all European
// countries, Australia, and one preferred country for now. This lets us
// quickly re-enable others later without losing data.

export type CountryCode = {
  code: string;
  country: string;
  flag: string;
  isoCode: string;
  minDigits: number;
  maxDigits: number;
};

// Full master list (do not remove). Think of the non-exported entries as
// "commented out" from the public export by way of filtering below.
const ALL_COUNTRY_CODES: CountryCode[] = [
  // A
  {
    code: "+93",
    country: "Afghanistan",
    flag: "🇦🇫",
    isoCode: "AF",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+355",
    country: "Albania",
    flag: "🇦🇱",
    isoCode: "AL",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+213",
    country: "Algeria",
    flag: "🇩🇿",
    isoCode: "DZ",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+1-684",
    country: "American Samoa",
    flag: "🇦🇸",
    isoCode: "AS",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+376",
    country: "Andorra",
    flag: "🇦🇩",
    isoCode: "AD",
    minDigits: 6,
    maxDigits: 9,
  },
  {
    code: "+244",
    country: "Angola",
    flag: "🇦🇴",
    isoCode: "AO",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+1-264",
    country: "Anguilla",
    flag: "🇦🇮",
    isoCode: "AI",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+1-268",
    country: "Antigua and Barbuda",
    flag: "🇦🇬",
    isoCode: "AG",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+54",
    country: "Argentina",
    flag: "🇦🇷",
    isoCode: "AR",
    minDigits: 10,
    maxDigits: 11,
  },
  {
    code: "+374",
    country: "Armenia",
    flag: "🇦🇲",
    isoCode: "AM",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+297",
    country: "Aruba",
    flag: "🇦🇼",
    isoCode: "AW",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+61",
    country: "Australia",
    flag: "🇦🇺",
    isoCode: "AU",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+43",
    country: "Austria",
    flag: "🇦🇹",
    isoCode: "AT",
    minDigits: 10,
    maxDigits: 13,
  },
  {
    code: "+994",
    country: "Azerbaijan",
    flag: "🇦🇿",
    isoCode: "AZ",
    minDigits: 9,
    maxDigits: 9,
  },

  // B
  {
    code: "+1-242",
    country: "Bahamas",
    flag: "🇧🇸",
    isoCode: "BS",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+973",
    country: "Bahrain",
    flag: "🇧🇭",
    isoCode: "BH",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+880",
    country: "Bangladesh",
    flag: "🇧🇩",
    isoCode: "BD",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+1-246",
    country: "Barbados",
    flag: "🇧🇧",
    isoCode: "BB",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+375",
    country: "Belarus",
    flag: "🇧🇾",
    isoCode: "BY",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+32",
    country: "Belgium",
    flag: "🇧🇪",
    isoCode: "BE",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+501",
    country: "Belize",
    flag: "🇧🇿",
    isoCode: "BZ",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+229",
    country: "Benin",
    flag: "🇧🇯",
    isoCode: "BJ",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+1-441",
    country: "Bermuda",
    flag: "🇧🇲",
    isoCode: "BM",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+975",
    country: "Bhutan",
    flag: "🇧🇹",
    isoCode: "BT",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+591",
    country: "Bolivia",
    flag: "🇧🇴",
    isoCode: "BO",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+387",
    country: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    isoCode: "BA",
    minDigits: 8,
    maxDigits: 9,
  },
  {
    code: "+267",
    country: "Botswana",
    flag: "🇧🇼",
    isoCode: "BW",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+55",
    country: "Brazil",
    flag: "🇧🇷",
    isoCode: "BR",
    minDigits: 10,
    maxDigits: 11,
  },
  {
    code: "+246",
    country: "British Indian Ocean Territory",
    flag: "🇮🇴",
    isoCode: "IO",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+1-284",
    country: "British Virgin Islands",
    flag: "🇻🇬",
    isoCode: "VG",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+673",
    country: "Brunei",
    flag: "🇧🇳",
    isoCode: "BN",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+359",
    country: "Bulgaria",
    flag: "🇧🇬",
    isoCode: "BG",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+226",
    country: "Burkina Faso",
    flag: "🇧🇫",
    isoCode: "BF",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+257",
    country: "Burundi",
    flag: "🇧🇮",
    isoCode: "BI",
    minDigits: 8,
    maxDigits: 8,
  },

  // C
  {
    code: "+855",
    country: "Cambodia",
    flag: "🇰🇭",
    isoCode: "KH",
    minDigits: 8,
    maxDigits: 9,
  },
  {
    code: "+237",
    country: "Cameroon",
    flag: "🇨🇲",
    isoCode: "CM",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+1-CA",
    country: "Canada",
    flag: "🇨🇦",
    isoCode: "CA",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+238",
    country: "Cape Verde",
    flag: "🇨🇻",
    isoCode: "CV",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+1-345",
    country: "Cayman Islands",
    flag: "🇰🇾",
    isoCode: "KY",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+236",
    country: "Central African Republic",
    flag: "🇨🇫",
    isoCode: "CF",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+235",
    country: "Chad",
    flag: "🇹🇩",
    isoCode: "TD",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+56",
    country: "Chile",
    flag: "🇨🇱",
    isoCode: "CL",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+86",
    country: "China",
    flag: "🇨🇳",
    isoCode: "CN",
    minDigits: 11,
    maxDigits: 11,
  },
  {
    code: "+61-8",
    country: "Christmas Island",
    flag: "🇨🇽",
    isoCode: "CX",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+61-9",
    country: "Cocos Islands",
    flag: "🇨🇨",
    isoCode: "CC",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+57",
    country: "Colombia",
    flag: "🇨🇴",
    isoCode: "CO",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+269",
    country: "Comoros",
    flag: "🇰🇲",
    isoCode: "KM",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+682",
    country: "Cook Islands",
    flag: "🇨🇰",
    isoCode: "CK",
    minDigits: 5,
    maxDigits: 5,
  },
  {
    code: "+506",
    country: "Costa Rica",
    flag: "🇨🇷",
    isoCode: "CR",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+385",
    country: "Croatia",
    flag: "🇭🇷",
    isoCode: "HR",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+53",
    country: "Cuba",
    flag: "🇨🇺",
    isoCode: "CU",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+599",
    country: "Curaçao",
    flag: "🇨🇼",
    isoCode: "CW",
    minDigits: 7,
    maxDigits: 8,
  },
  {
    code: "+357",
    country: "Cyprus",
    flag: "🇨🇾",
    isoCode: "CY",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+420",
    country: "Czech Republic",
    flag: "🇨🇿",
    isoCode: "CZ",
    minDigits: 9,
    maxDigits: 9,
  },

  // D
  {
    code: "+243",
    country: "Democratic Republic of the Congo",
    flag: "🇨🇩",
    isoCode: "CD",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+45",
    country: "Denmark",
    flag: "🇩🇰",
    isoCode: "DK",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+253",
    country: "Djibouti",
    flag: "🇩🇯",
    isoCode: "DJ",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+1-767",
    country: "Dominica",
    flag: "🇩🇲",
    isoCode: "DM",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+1-809",
    country: "Dominican Republic",
    flag: "🇩🇴",
    isoCode: "DO",
    minDigits: 10,
    maxDigits: 10,
  },

  // E
  {
    code: "+593",
    country: "Ecuador",
    flag: "🇪🇨",
    isoCode: "EC",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+20",
    country: "Egypt",
    flag: "🇪🇬",
    isoCode: "EG",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+503",
    country: "El Salvador",
    flag: "🇸🇻",
    isoCode: "SV",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+240",
    country: "Equatorial Guinea",
    flag: "🇬🇶",
    isoCode: "GQ",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+291",
    country: "Eritrea",
    flag: "🇪🇷",
    isoCode: "ER",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+372",
    country: "Estonia",
    flag: "🇪🇪",
    isoCode: "EE",
    minDigits: 7,
    maxDigits: 8,
  },
  {
    code: "+268",
    country: "Eswatini",
    flag: "🇸🇿",
    isoCode: "SZ",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+251",
    country: "Ethiopia",
    flag: "🇪🇹",
    isoCode: "ET",
    minDigits: 9,
    maxDigits: 9,
  },

  // F
  {
    code: "+500",
    country: "Falkland Islands",
    flag: "🇫🇰",
    isoCode: "FK",
    minDigits: 5,
    maxDigits: 5,
  },
  {
    code: "+298",
    country: "Faroe Islands",
    flag: "🇫🇴",
    isoCode: "FO",
    minDigits: 6,
    maxDigits: 6,
  },
  {
    code: "+679",
    country: "Fiji",
    flag: "🇫🇯",
    isoCode: "FJ",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+358",
    country: "Finland",
    flag: "🇫🇮",
    isoCode: "FI",
    minDigits: 9,
    maxDigits: 10,
  },
  {
    code: "+33",
    country: "France",
    flag: "🇫🇷",
    isoCode: "FR",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+594",
    country: "French Guiana",
    flag: "🇬🇫",
    isoCode: "GF",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+689",
    country: "French Polynesia",
    flag: "🇵🇫",
    isoCode: "PF",
    minDigits: 6,
    maxDigits: 6,
  },

  // G
  {
    code: "+241",
    country: "Gabon",
    flag: "🇬🇦",
    isoCode: "GA",
    minDigits: 7,
    maxDigits: 8,
  },
  {
    code: "+220",
    country: "Gambia",
    flag: "🇬🇲",
    isoCode: "GM",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+995",
    country: "Georgia",
    flag: "🇬🇪",
    isoCode: "GE",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+49",
    country: "Germany",
    flag: "🇩🇪",
    isoCode: "DE",
    minDigits: 10,
    maxDigits: 13,
  },
  {
    code: "+233",
    country: "Ghana",
    flag: "🇬🇭",
    isoCode: "GH",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+350",
    country: "Gibraltar",
    flag: "🇬🇮",
    isoCode: "GI",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+30",
    country: "Greece",
    flag: "🇬🇷",
    isoCode: "GR",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+299",
    country: "Greenland",
    flag: "🇬🇱",
    isoCode: "GL",
    minDigits: 6,
    maxDigits: 6,
  },
  {
    code: "+1-473",
    country: "Grenada",
    flag: "🇬🇩",
    isoCode: "GD",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+590",
    country: "Guadeloupe",
    flag: "🇬🇵",
    isoCode: "GP",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+1-671",
    country: "Guam",
    flag: "🇬🇺",
    isoCode: "GU",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+502",
    country: "Guatemala",
    flag: "🇬🇹",
    isoCode: "GT",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+44-1481",
    country: "Guernsey",
    flag: "🇬🇬",
    isoCode: "GG",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+224",
    country: "Guinea",
    flag: "🇬🇳",
    isoCode: "GN",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+245",
    country: "Guinea-Bissau",
    flag: "🇬🇼",
    isoCode: "GW",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+592",
    country: "Guyana",
    flag: "🇬🇾",
    isoCode: "GY",
    minDigits: 7,
    maxDigits: 7,
  },

  // H
  {
    code: "+509",
    country: "Haiti",
    flag: "🇭🇹",
    isoCode: "HT",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+504",
    country: "Honduras",
    flag: "🇭🇳",
    isoCode: "HN",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+852",
    country: "Hong Kong",
    flag: "🇭🇰",
    isoCode: "HK",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+36",
    country: "Hungary",
    flag: "🇭🇺",
    isoCode: "HU",
    minDigits: 9,
    maxDigits: 9,
  },

  // I
  {
    code: "+354",
    country: "Iceland",
    flag: "🇮🇸",
    isoCode: "IS",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+91",
    country: "India",
    flag: "🇮🇳",
    isoCode: "IN",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+62",
    country: "Indonesia",
    flag: "🇮🇩",
    isoCode: "ID",
    minDigits: 9,
    maxDigits: 12,
  },
  {
    code: "+98",
    country: "Iran",
    flag: "🇮🇷",
    isoCode: "IR",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+964",
    country: "Iraq",
    flag: "🇮🇶",
    isoCode: "IQ",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+353",
    country: "Ireland",
    flag: "🇮🇪",
    isoCode: "IE",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+44-1624",
    country: "Isle of Man",
    flag: "🇮🇲",
    isoCode: "IM",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+972",
    country: "Israel",
    flag: "🇮🇱",
    isoCode: "IL",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+39",
    country: "Italy",
    flag: "🇮🇹",
    isoCode: "IT",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+225",
    country: "Ivory Coast",
    flag: "🇨🇮",
    isoCode: "CI",
    minDigits: 8,
    maxDigits: 8,
  },

  // J
  {
    code: "+1-876",
    country: "Jamaica",
    flag: "🇯🇲",
    isoCode: "JM",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+81",
    country: "Japan",
    flag: "🇯🇵",
    isoCode: "JP",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+44-1534",
    country: "Jersey",
    flag: "🇯🇪",
    isoCode: "JE",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+962",
    country: "Jordan",
    flag: "🇯🇴",
    isoCode: "JO",
    minDigits: 9,
    maxDigits: 9,
  },

  // K
  {
    code: "+7",
    country: "Kazakhstan",
    flag: "🇰🇿",
    isoCode: "KZ",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+254",
    country: "Kenya",
    flag: "🇰🇪",
    isoCode: "KE",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+686",
    country: "Kiribati",
    flag: "🇰🇮",
    isoCode: "KI",
    minDigits: 5,
    maxDigits: 5,
  },
  {
    code: "+383",
    country: "Kosovo",
    flag: "🇽🇰",
    isoCode: "XK",
    minDigits: 8,
    maxDigits: 9,
  },
  {
    code: "+965",
    country: "Kuwait",
    flag: "🇰🇼",
    isoCode: "KW",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+996",
    country: "Kyrgyzstan",
    flag: "🇰🇬",
    isoCode: "KG",
    minDigits: 9,
    maxDigits: 9,
  },

  // L
  {
    code: "+856",
    country: "Laos",
    flag: "🇱🇦",
    isoCode: "LA",
    minDigits: 9,
    maxDigits: 10,
  },
  {
    code: "+371",
    country: "Latvia",
    flag: "🇱🇻",
    isoCode: "LV",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+961",
    country: "Lebanon",
    flag: "🇱🇧",
    isoCode: "LB",
    minDigits: 7,
    maxDigits: 8,
  },
  {
    code: "+266",
    country: "Lesotho",
    flag: "🇱🇸",
    isoCode: "LS",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+231",
    country: "Liberia",
    flag: "🇱🇷",
    isoCode: "LR",
    minDigits: 7,
    maxDigits: 9,
  },
  {
    code: "+218",
    country: "Libya",
    flag: "🇱🇾",
    isoCode: "LY",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+423",
    country: "Liechtenstein",
    flag: "🇱🇮",
    isoCode: "LI",
    minDigits: 7,
    maxDigits: 9,
  },
  {
    code: "+370",
    country: "Lithuania",
    flag: "🇱🇹",
    isoCode: "LT",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+352",
    country: "Luxembourg",
    flag: "🇱🇺",
    isoCode: "LU",
    minDigits: 9,
    maxDigits: 9,
  },

  // M
  {
    code: "+853",
    country: "Macau",
    flag: "🇲🇴",
    isoCode: "MO",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+389",
    country: "North Macedonia",
    flag: "🇲🇰",
    isoCode: "MK",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+261",
    country: "Madagascar",
    flag: "🇲🇬",
    isoCode: "MG",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+265",
    country: "Malawi",
    flag: "🇲🇼",
    isoCode: "MW",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+60",
    country: "Malaysia",
    flag: "🇲🇾",
    isoCode: "MY",
    minDigits: 9,
    maxDigits: 10,
  },
  {
    code: "+960",
    country: "Maldives",
    flag: "🇲🇻",
    isoCode: "MV",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+223",
    country: "Mali",
    flag: "🇲🇱",
    isoCode: "ML",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+356",
    country: "Malta",
    flag: "🇲🇹",
    isoCode: "MT",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+692",
    country: "Marshall Islands",
    flag: "🇲🇭",
    isoCode: "MH",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+596",
    country: "Martinique",
    flag: "🇲🇶",
    isoCode: "MQ",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+222",
    country: "Mauritania",
    flag: "🇲🇷",
    isoCode: "MR",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+230",
    country: "Mauritius",
    flag: "🇲🇺",
    isoCode: "MU",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+262",
    country: "Mayotte",
    flag: "🇾🇹",
    isoCode: "YT",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+52",
    country: "Mexico",
    flag: "🇲🇽",
    isoCode: "MX",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+691",
    country: "Micronesia",
    flag: "🇫🇲",
    isoCode: "FM",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+373",
    country: "Moldova",
    flag: "🇲🇩",
    isoCode: "MD",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+377",
    country: "Monaco",
    flag: "🇲🇨",
    isoCode: "MC",
    minDigits: 8,
    maxDigits: 9,
  },
  {
    code: "+976",
    country: "Mongolia",
    flag: "🇲🇳",
    isoCode: "MN",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+382",
    country: "Montenegro",
    flag: "🇲🇪",
    isoCode: "ME",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+1-664",
    country: "Montserrat",
    flag: "🇲🇸",
    isoCode: "MS",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+212",
    country: "Morocco",
    flag: "🇲🇦",
    isoCode: "MA",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+258",
    country: "Mozambique",
    flag: "🇲🇿",
    isoCode: "MZ",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+95",
    country: "Myanmar",
    flag: "🇲🇲",
    isoCode: "MM",
    minDigits: 8,
    maxDigits: 10,
  },
  {
    code: "+212-2",
    country: "Western Sahara",
    flag: "🇪🇭",
    isoCode: "EH",
    minDigits: 9,
    maxDigits: 9,
  },

  // N
  {
    code: "+264",
    country: "Namibia",
    flag: "🇳🇦",
    isoCode: "NA",
    minDigits: 9,
    maxDigits: 10,
  },
  {
    code: "+674",
    country: "Nauru",
    flag: "🇳🇷",
    isoCode: "NR",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+977",
    country: "Nepal",
    flag: "🇳🇵",
    isoCode: "NP",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+31",
    country: "Netherlands",
    flag: "🇳🇱",
    isoCode: "NL",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+687",
    country: "New Caledonia",
    flag: "🇳🇨",
    isoCode: "NC",
    minDigits: 6,
    maxDigits: 6,
  },
  {
    code: "+64",
    country: "New Zealand",
    flag: "🇳🇿",
    isoCode: "NZ",
    minDigits: 9,
    maxDigits: 10,
  },
  {
    code: "+505",
    country: "Nicaragua",
    flag: "🇳🇮",
    isoCode: "NI",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+227",
    country: "Niger",
    flag: "🇳🇪",
    isoCode: "NE",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+234",
    country: "Nigeria",
    flag: "🇳🇬",
    isoCode: "NG",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+683",
    country: "Niue",
    flag: "🇳🇺",
    isoCode: "NU",
    minDigits: 4,
    maxDigits: 4,
  },
  {
    code: "+672",
    country: "Norfolk Island",
    flag: "🇳🇫",
    isoCode: "NF",
    minDigits: 5,
    maxDigits: 6,
  },
  {
    code: "+850",
    country: "North Korea",
    flag: "🇰🇵",
    isoCode: "KP",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+1-670",
    country: "Northern Mariana Islands",
    flag: "🇲🇵",
    isoCode: "MP",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+47",
    country: "Norway",
    flag: "🇳🇴",
    isoCode: "NO",
    minDigits: 8,
    maxDigits: 8,
  },

  // O
  {
    code: "+968",
    country: "Oman",
    flag: "🇴🇲",
    isoCode: "OM",
    minDigits: 8,
    maxDigits: 8,
  },

  // P
  {
    code: "+92",
    country: "Pakistan",
    flag: "🇵🇰",
    isoCode: "PK",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+680",
    country: "Palau",
    flag: "🇵🇼",
    isoCode: "PW",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+970",
    country: "Palestine",
    flag: "🇵🇸",
    isoCode: "PS",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+507",
    country: "Panama",
    flag: "🇵🇦",
    isoCode: "PA",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+675",
    country: "Papua New Guinea",
    flag: "🇵🇬",
    isoCode: "PG",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+595",
    country: "Paraguay",
    flag: "🇵🇾",
    isoCode: "PY",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+51",
    country: "Peru",
    flag: "🇵🇪",
    isoCode: "PE",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+63",
    country: "Philippines",
    flag: "🇵🇭",
    isoCode: "PH",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+48",
    country: "Poland",
    flag: "🇵🇱",
    isoCode: "PL",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+351",
    country: "Portugal",
    flag: "🇵🇹",
    isoCode: "PT",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+1-787",
    country: "Puerto Rico",
    flag: "🇵🇷",
    isoCode: "PR",
    minDigits: 10,
    maxDigits: 10,
  },

  // Q
  {
    code: "+974",
    country: "Qatar",
    flag: "🇶🇦",
    isoCode: "QA",
    minDigits: 8,
    maxDigits: 8,
  },

  // R
  {
    code: "+242",
    country: "Republic of the Congo",
    flag: "🇨🇬",
    isoCode: "CG",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+262-1",
    country: "Réunion",
    flag: "🇷🇪",
    isoCode: "RE",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+40",
    country: "Romania",
    flag: "🇷🇴",
    isoCode: "RO",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+7-6",
    country: "Russia",
    flag: "🇷🇺",
    isoCode: "RU",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+250",
    country: "Rwanda",
    flag: "🇷🇼",
    isoCode: "RW",
    minDigits: 9,
    maxDigits: 9,
  },

  // S
  {
    code: "+590-2",
    country: "Saint Barthélemy",
    flag: "🇧🇱",
    isoCode: "BL",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+290",
    country: "Saint Helena",
    flag: "🇸🇭",
    isoCode: "SH",
    minDigits: 4,
    maxDigits: 4,
  },
  {
    code: "+1-869",
    country: "Saint Kitts and Nevis",
    flag: "🇰🇳",
    isoCode: "KN",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+1-758",
    country: "Saint Lucia",
    flag: "🇱🇨",
    isoCode: "LC",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+590-1",
    country: "Saint Martin",
    flag: "🇲🇫",
    isoCode: "MF",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+508",
    country: "Saint Pierre and Miquelon",
    flag: "🇵🇲",
    isoCode: "PM",
    minDigits: 6,
    maxDigits: 6,
  },
  {
    code: "+1-784",
    country: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    isoCode: "VC",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+685",
    country: "Samoa",
    flag: "🇼🇸",
    isoCode: "WS",
    minDigits: 5,
    maxDigits: 7,
  },
  {
    code: "+378",
    country: "San Marino",
    flag: "🇸🇲",
    isoCode: "SM",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+239",
    country: "São Tomé and Príncipe",
    flag: "🇸🇹",
    isoCode: "ST",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+966",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    isoCode: "SA",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+221",
    country: "Senegal",
    flag: "🇸🇳",
    isoCode: "SN",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+381",
    country: "Serbia",
    flag: "🇷🇸",
    isoCode: "RS",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+248",
    country: "Seychelles",
    flag: "🇸🇨",
    isoCode: "SC",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+232",
    country: "Sierra Leone",
    flag: "🇸🇱",
    isoCode: "SL",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+65",
    country: "Singapore",
    flag: "🇸🇬",
    isoCode: "SG",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+1-721",
    country: "Sint Maarten",
    flag: "🇸🇽",
    isoCode: "SX",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+421",
    country: "Slovakia",
    flag: "🇸🇰",
    isoCode: "SK",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+386",
    country: "Slovenia",
    flag: "🇸🇮",
    isoCode: "SI",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+677",
    country: "Solomon Islands",
    flag: "🇸🇧",
    isoCode: "SB",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+252",
    country: "Somalia",
    flag: "🇸🇴",
    isoCode: "SO",
    minDigits: 8,
    maxDigits: 9,
  },
  {
    code: "+27",
    country: "South Africa",
    flag: "🇿🇦",
    isoCode: "ZA",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+82",
    country: "South Korea",
    flag: "🇰🇷",
    isoCode: "KR",
    minDigits: 9,
    maxDigits: 10,
  },
  {
    code: "+211",
    country: "South Sudan",
    flag: "🇸🇸",
    isoCode: "SS",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+34",
    country: "Spain",
    flag: "🇪🇸",
    isoCode: "ES",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+94",
    country: "Sri Lanka",
    flag: "🇱🇰",
    isoCode: "LK",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+249",
    country: "Sudan",
    flag: "🇸🇩",
    isoCode: "SD",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+597",
    country: "Suriname",
    flag: "🇸🇷",
    isoCode: "SR",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+47-1",
    country: "Svalbard and Jan Mayen",
    flag: "🇸🇯",
    isoCode: "SJ",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+46",
    country: "Sweden",
    flag: "🇸🇪",
    isoCode: "SE",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+41",
    country: "Switzerland",
    flag: "🇨🇭",
    isoCode: "CH",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+963",
    country: "Syria",
    flag: "🇸🇾",
    isoCode: "SY",
    minDigits: 9,
    maxDigits: 9,
  },

  // T
  {
    code: "+886",
    country: "Taiwan",
    flag: "🇹🇼",
    isoCode: "TW",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+992",
    country: "Tajikistan",
    flag: "🇹🇯",
    isoCode: "TJ",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+255",
    country: "Tanzania",
    flag: "🇹🇿",
    isoCode: "TZ",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+66",
    country: "Thailand",
    flag: "🇹🇭",
    isoCode: "TH",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+670",
    country: "Timor-Leste",
    flag: "🇹🇱",
    isoCode: "TL",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+228",
    country: "Togo",
    flag: "🇹🇬",
    isoCode: "TG",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+690",
    country: "Tokelau",
    flag: "🇹🇰",
    isoCode: "TK",
    minDigits: 4,
    maxDigits: 4,
  },
  {
    code: "+676",
    country: "Tonga",
    flag: "🇹🇴",
    isoCode: "TO",
    minDigits: 5,
    maxDigits: 7,
  },
  {
    code: "+1-868",
    country: "Trinidad and Tobago",
    flag: "🇹🇹",
    isoCode: "TT",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+216",
    country: "Tunisia",
    flag: "🇹🇳",
    isoCode: "TN",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+90",
    country: "Turkey",
    flag: "🇹🇷",
    isoCode: "TR",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+993",
    country: "Turkmenistan",
    flag: "🇹🇲",
    isoCode: "TM",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+1-649",
    country: "Turks and Caicos Islands",
    flag: "🇹🇨",
    isoCode: "TC",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+688",
    country: "Tuvalu",
    flag: "🇹🇻",
    isoCode: "TV",
    minDigits: 5,
    maxDigits: 6,
  },

  // U
  {
    code: "+256",
    country: "Uganda",
    flag: "🇺🇬",
    isoCode: "UG",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+380",
    country: "Ukraine",
    flag: "🇺🇦",
    isoCode: "UA",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+971",
    country: "United Arab Emirates",
    flag: "🇦🇪",
    isoCode: "AE",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+44",
    country: "United Kingdom",
    flag: "🇬🇧",
    isoCode: "GB",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+1",
    country: "United States",
    flag: "🇺🇸",
    isoCode: "US",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+598",
    country: "Uruguay",
    flag: "🇺🇾",
    isoCode: "UY",
    minDigits: 8,
    maxDigits: 8,
  },
  {
    code: "+1-340",
    country: "US Virgin Islands",
    flag: "🇻🇮",
    isoCode: "VI",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+998",
    country: "Uzbekistan",
    flag: "🇺🇿",
    isoCode: "UZ",
    minDigits: 9,
    maxDigits: 9,
  },

  // V
  {
    code: "+678",
    country: "Vanuatu",
    flag: "🇻🇺",
    isoCode: "VU",
    minDigits: 7,
    maxDigits: 7,
  },
  {
    code: "+379",
    country: "Vatican City",
    flag: "🇻🇦",
    isoCode: "VA",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+58",
    country: "Venezuela",
    flag: "🇻🇪",
    isoCode: "VE",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "+84",
    country: "Vietnam",
    flag: "🇻🇳",
    isoCode: "VN",
    minDigits: 9,
    maxDigits: 10,
  },
  {
    code: "+681",
    country: "Wallis and Futuna",
    flag: "🇼🇫",
    isoCode: "WF",
    minDigits: 6,
    maxDigits: 6,
  },

  // Y
  {
    code: "+967",
    country: "Yemen",
    flag: "🇾🇪",
    isoCode: "YE",
    minDigits: 9,
    maxDigits: 9,
  },

  // Z
  {
    code: "+260",
    country: "Zambia",
    flag: "🇿🇲",
    isoCode: "ZM",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "+263",
    country: "Zimbabwe",
    flag: "🇿🇼",
    isoCode: "ZW",
    minDigits: 9,
    maxDigits: 9,
  },
];

// Europe ISO codes present in this list (including crown dependencies/territories in Europe)
const EUROPE_ISO_CODES = [
  "AL", // Albania
  "AD", // Andorra
  "AT", // Austria
  "BY", // Belarus
  "BE", // Belgium
  "BA", // Bosnia and Herzegovina
  "BG", // Bulgaria
  "HR", // Croatia
  "CY", // Cyprus
  "CZ", // Czech Republic
  "DK", // Denmark
  "EE", // Estonia
  "FO", // Faroe Islands
  "FI", // Finland
  "FR", // France
  "DE", // Germany
  "GI", // Gibraltar
  "GR", // Greece
  "GG", // Guernsey
  "HU", // Hungary
  "IS", // Iceland
  "IE", // Ireland
  "IM", // Isle of Man
  "IT", // Italy
  "JE", // Jersey
  "XK", // Kosovo
  "LV", // Latvia
  "LI", // Liechtenstein
  "LT", // Lithuania
  "LU", // Luxembourg
  "MK", // North Macedonia
  "MT", // Malta
  "MC", // Monaco
  "ME", // Montenegro
  "NL", // Netherlands
  "NO", // Norway
  "PL", // Poland
  "PT", // Portugal
  "RO", // Romania
  "RU", // Russia
  "SM", // San Marino
  "RS", // Serbia
  "SK", // Slovakia
  "SI", // Slovenia
  "ES", // Spain
  "SJ", // Svalbard and Jan Mayen
  "SE", // Sweden
  "CH", // Switzerland
  "UA", // Ukraine
  "GB", // United Kingdom
  "VA", // Vatican City
];

// Preferred extra country to keep visible for now (project context: Bengali primary)
const PREFERRED_ISO_CODES = ["BD"]; // Bangladesh

const ALLOWED_ISO_CODES = new Set<string>([
  ...EUROPE_ISO_CODES,
  "US", // United States
  "CA", // Canada
  "AU", // Australia
  ...PREFERRED_ISO_CODES,
]);

export const COUNTRY_CODES: CountryCode[] = ALL_COUNTRY_CODES.filter((c) =>
  ALLOWED_ISO_CODES.has(c.isoCode)
);
